# Generated by Django 5.2.3 on 2025-06-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.PositiveIntegerField(default=4830),
        ),
    ]
