# Generated by Django 5.2.3 on 2025-06-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='file',
            name='expire_hours',
            field=models.PositiveIntegerField(default=24, help_text="Necha soatdan keyin o'chiriladi"),
        ),
    ]
