# Generated by Django 5.2.3 on 2025-06-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_remove_file_expires_at_file_expire_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='link',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
