# Generated by Django 5.2.3 on 2025-06-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_file_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileaccesslog',
            name='location',
        ),
    ]
